### ISSUE TITLE
Controlling Heater

### ISSUE THREAD

**Issue by Kinick4** [ostaquet/Arduino-MQ131-driver#1]
Hi!
First of all: Thanks for doing this!
My readings were primary temperature. 
I will test your library later on today, but it seems to be the best one you can find on the net.

But I have on question: Do I really need to control the heater or can I power it 24/7?

Best regards
Niklas

**Comment by ostaquet** [comment]
Hi,
The control of the heater is done only the time required to get consistent values from the sensor. The method begin() is starting the heater for the time required, capture the value and stop the heater.
You can power it 24/7 but to do that, you should extend the class and use the protected methods startHeater(), readRs() and stopHeater().
KR,
Olivier
