### ISSUE TITLE
Can I change the "Delay(60000);" on the Loop?

### ISSUE THREAD

**Issue by fcbaccha** [ostaquet/Arduino-MQ131-driver#10]
Hello,
Congratulations for your library, veru good job! I wanted to ask you if it is possible to change (reduce) the delay(6000) on the loop? A lot of time goes by between the delay and the measure time (72 seconds) and I need it shorter. 
Thanks in advance,
Francisco

**Comment by ostaquet** [comment]
Hi,
This question was already answered in #3 .
Remember how the sensor is working ;-)
KR
