### ISSUE TITLE
calibration time

### ISSUE THREAD

**Issue by CAMR94** [ostaquet/Arduino-MQ131-driver#11]
One Question. How long does the calibration usually take? My Sensors heat up proberly and seem fine, but the calibration has been running for half the day now and nothing happened. Is it calibrating for the whole 48h?

**Comment by ostaquet** [comment]
The calibration process should be quite rapid (max 10 minutes).

The calibration process as built in the library works by heating the sensor for 15-20 seconds (depending on the sensor type) and measuring the value every seconds. At each cycle, we stored the value read on the sensor. As soon as the value is stable, we know the stabilization cycle of the sensor. It defined the R0 and the time to read.

Did you preheat your sensor? (burn time of 48h)

**Comment by CAMR94** [comment]
I have not burned it in completely yet. it is running right now with the calibration in the background and it should be finished tomorrow morning. 

Is that burn in time necessary only once, or every time, that you are using it?

**Comment by ostaquet** [comment]
Burn in time is required only once.
You should rerun the calibration after the burn in time.
If you have still problem, we have to investigate why the reading value is unstable.

**Comment by CAMR94** [comment]
So I left it running and started the calibration again, after the burn in time. 
Still the calibration is not finishing. 

I added some Pictures of my Setup. It's a mess, but maybe you can see something, that I can't. 
Thank you again for your help.
![S2](https://user-images.githubusercontent.com/46993110/62632288-8907bd80-b932-11e9-851a-39f626eb2f58.jpg)
![S3](https://user-images.githubusercontent.com/46993110/62632290-8907bd80-b932-11e9-846a-5c1dfbabda39.jpg)
![S1](https://user-images.githubusercontent.com/46993110/62632291-8907bd80-b932-11e9-9c42-039c35127f29.jpg)

**Comment by ostaquet** [comment]
I didn't check in details your wiring. I have just some doubts about the power. It seems that you power everything through the USB of the computer, which is maybe not enough. I personally use the additional jack power to give enough power to the wiring.

In order to understand what is happening, you should add this after the line 246 in the MQ131.cpp file :
`Serial.println(value);`

It will give you an idea of the readings on the analog input.

**Comment by CAMR94** [comment]
Hello again. Sorry for the late answer, I was gone for a few days.

I did add the jack, but still the Calibration doesn't finish.
I also added the Line and I am getting some readouts now. 

Here are some Images of the Readout at the start and roughly 10-15 minutes later.

![r1](https://user-images.githubusercontent.com/46993110/63005169-471fcf80-be7c-11e9-847a-0113c02f95ac.PNG)
![r2](https://user-images.githubusercontent.com/46993110/63005170-471fcf80-be7c-11e9-9c12-4a739c89fe91.PNG)

**Comment by ostaquet** [comment]
The variance is important and unusual. When I looked to your last output, we have the same values coming out : `1127777.75`, `1014000.00` and `920909.12`. During the calibration process, the code is expecting a stable value.

What is the board that you're using?
What is the load resistance you're using?

**Comment by CAMR94** [comment]
https://ardubotics.eu/en/microcontrollers/150-sainsmart-uno-r3-atmega328p-development-board-compatible-with-arduino-uno-r3.html This is the Board that I'm using.

I have replicated your Setup exactly, so my resistors are the same. I set it up multiple times with the same results.

**Comment by ostaquet** [comment]
I retest the whole code and made some technical refactoring. I don't see why your sensor is driving crazy during the calibration process.
Please check the connections as described in the README (I added the MQ131 pinout on a schema).
If you used a wrong connection on the pinouts, you had maybe damage the lead in the sensor. :-(

**Comment by atlask1** [comment]
Hi  @CAMR94 ,
it's easy that you have damage the sensor, maybe you have powered it with wrong wiring. If you read the datasheet you could understand it. It's a supposition , but could happen.

![mq131_ds_screnshoot](https://user-images.githubusercontent.com/26408373/64176715-4916f600-ce5e-11e9-98b8-af9a771401bf.png)

this is extremely situation, but strange behaviour happen if it's partially damaged, like unstable value.
