### ISSUE TITLE
Why using a RL of 10K and not a 1M as in datsheets?

### ISSUE THREAD

**Issue by msillano** [ostaquet/Arduino-MQ131-driver#13]

**Comment by ostaquet** [comment]
hi, good code mr. ostaquet.  Only one question: why you use a RL of 10K and not a 1M as in datsheets?  Best regards, m.s.

Originally posted by @msillano

**Comment by ostaquet** [comment]
Hi @msillano,
The load resistance is not so important in the process as far as it is not too small. 10K Ohms is working but it is true that the datasheet recommend 1M Ohms. To follow the datasheet, I updated the library and cleanup a bit the code.
Thanks for raising this point.
KR.
