### ISSUE TITLE
measuring volume

### ISSUE THREAD

**Issue by CarlosFonseca97** [ostaquet/Arduino-MQ131-driver#15]
Hello, my name is Carlos Fonseca, I am from Colombia, I am sorry for my writing in English.

My question is to find out if anyone knows the volume of measurement that the MQ sensors have, specifically the MQ131, and also use two simultaneously to average them within a cavity with a volume of 2.7m^3.

Thanks to Ostaget for this efficient library.

**Comment by ostaquet** [comment]
As the MQ131 is a semiconductor sensor, the measurement volume is not relevant. Indeed, this type of sensor detects gases by a chemical reaction that takes place when the gas comes in direct contact with the sensor.

My guess (but I'm not a specialist) is that the measurement of the sensor is limited to the close proximity of the sensor. If you want to measure the O3 in a bigger volume, you should use multiple sensors and consolidate the results.
