### ISSUE TITLE
Wiring

### ISSUE THREAD

**Issue by SciWax** [ostaquet/Arduino-MQ131-driver#16]
Hey ostaquet,

firstly thanks for the information you give about the sensor and the cool library. I have a question in regards of the wiring. Online it's often recommended to wire all pins, while the datasheet implies not to do that, if I understood it correctly.

Fir instance here: https://playground.arduino.cc/Main/MQGasSensors/

Also the traces on this PCB from a manufacturer implies it's okay to wire everything: https://eckstein-shop.de/Pololu-Carrier-for-MQ-Gas-Sensors-Bare-PCB-Only

On the first glance, it looks like both ways are okay. What's your opinion on the issue?

Kind regards

**Comment by ostaquet** [comment]
In my experience, both are OK. You could wire everything or wire only what is required. It will not impact the results.
