### ISSUE TITLE
Deviation by factor 100 upwards

### ISSUE THREAD

**Issue by Kinick4** [ostaquet/Arduino-MQ131-driver#2]
Hi!
I have been testing your driver with my MQ131 and arduino uno.
I got a deviation by a factor of 100 upwards to a validate measuring.
Does anybody has a clue for me where it comes from?
Greetz Niklas

**Comment by ostaquet** [comment]
Hi,
What do you mean with deviation?
Remember that there is at least 3 known version of the MQ131:
 - Low concentration (black bakelite) commonly used for air pollution control.
 - High concentration (metal) for industrial purpose.
 - The "out-of-scope" one (blue bakelite), powered on 6V.
The high concentration version will never give you a valid value as the lower threshold is a concentration that we don't find in common environment.
KR,
Olivier
