### ISSUE TITLE
about the circuit

### ISSUE THREAD

**Issue by chedao24** [ostaquet/Arduino-MQ131-driver#22]
hi, i am reading this projects it's look awesome, thanks for the research, but i have a doubt about the circuit, in the fritzing model you conect te mq131 module heater to 5V and GND or you connect to 5V and drain of the mosfet?

**Comment by ostaquet** [comment]
The heater circuit is controlled by the N-channel MOSFET.

The heater is connected directly to the 5V and to the drain of the MOSFET. It is not connected to GND to avoid being on all the time (see also #21 ).
