### ISSUE TITLE
Use this library for others MQ-Sensors, it's possible?

### ISSUE THREAD

**Issue by ferreiradiego** [ostaquet/Arduino-MQ131-driver#24]
I'm participating in an Air Quality project, we are using many low cost sensors and among them there are: MQ131, MQ136, MQ2 and others. This library is really good for MQ131. I'm developing a library more generical to use MQ Sensors (of Winsen) and the whole my code is based on your and [Davide Gironi article](https://www.open-electronics.org/presenting-mq-sensors-low-cost-gas-and-pollution-detectors/l).
Do you think it's posible to develop a library (based on this) for others MQ Sensors as for example MQ136?

**Comment by ostaquet** [comment]
MQ-series sensors are quite similar to each others. It is possible to build a library to support all MQ sensors. The logic is still the same. The sensitivity curves, the environmental correction and the unit conversion need to be adapted but it is completely doable ;-)
