### ISSUE TITLE
Sensitivity curves

### ISSUE THREAD

**Issue by morfeus2** [ostaquet/Arduino-MQ131-driver#37]
Hello, thanks for the project, it's very interesting.
I would like to ask you: where did you get the calibration values presented in "Sensitivity curves" spreadsheet?

**Comment by dzvid** [comment]
@morfeus2 You mean the values in the tables?

**Comment by morfeus2** [comment]
Yes, exactly Rs/R0 vs ppm, Influence of Temperature/Humidity etc...
Were they measured by hand from the graphs in the official datasheet or something better?

**Comment by dzvid** [comment]
It was measured from datasheet curves, getting some points in the curve and applying linear regression to get sensor equations. 
As said here: #29

**Comment by ostaquet** [comment]
Indeed, as @dzvid wrote, the data points are coming from the data sheet and I applied a regression to get the best sensor equation.
