### ISSUE TITLE
Can we use MQ-131 module with 4 pins with the library? (instead of raw sensor with 6 pins)

### ISSUE THREAD

**Issue by lailomah** [ostaquet/Arduino-MQ131-driver#39]
Thankyou for an organized tutorial about MQ-131 I have few questions if someone could answer it will be so helpful.

1: Instead of using all 6 pins of heater and sensors Can we use this Sensor with the module that has 4 pins (VCC,GND, A0. D0) ?

2: How the library is calculating PPM? is it converting the analogue values into ppm?

**Comment by ostaquet** [comment]
1. The sensors have always 6 pins but only 4 are really used. I don't have the documentation of your module. So, it is difficult to know the parameters of the breakout module. Do you have some doc?

2. The result of the sensor is a resistance ratio. The resistance ratio is computed based on the sensitivity curves of the sensor as defined in the datasheet. The formula are in the Excel sheet (https://github.com/ostaquet/Arduino-MQ131-driver/blob/master/extras/datasheet/Sensitivity_curves.xlsx).

**Comment by damico** [comment]
I  believe that **lailomah** is talking about this board:

![image](https://user-images.githubusercontent.com/692043/134252057-46e0f0e2-844a-430e-8523-3c7c19741080.png)

Which can be understood by this circuit diagram:

![image](https://user-images.githubusercontent.com/692043/134251992-1a4e06e6-fc75-4fbb-a930-1e74458280fc.png)

Where the R2 is 1KOhm.

Best Regards,

Jose Damico
