### ISSUE TITLE
Mixed up formulas in the environmental correction ratio

### ISSUE THREAD

**Issue by JosephJohnZ** [ostaquet/Arduino-MQ131-driver#41]
Hello, while going through your code I noticed that the equations for 30% an 85% curves seem to be switched places.

**Comment by ostaquet** [comment]
Hi @JosephJohnZ,
Can you elaborate a bit?
Are you talking about environmental impact on the O3 level?

**Comment by JosephJohnZ** [comment]
Yes, I mean the formulas in getEnvCorrectRatio method, I checked with the excell file you provided and according to the graph there it seems that the formulas "For humidity > 75%, use the 85% curve" and "Humidity < 50%, use the 30% curve" in the .cpp file are switched. Unless I saw it wrong

**Comment by ostaquet** [comment]
You're right!

Just fixed in release 1.5.2.

Thanks for letting me know ;-)
