### ISSUE TITLE
Collection of data points in the data sheet to define equation

### ISSUE THREAD

**Issue by JosephJohnZ** [ostaquet/Arduino-MQ131-driver#42]
Hello once again, I was wondering how you got the data from the datasheet of the sensor, because the datasheet doesn't seem to provide actual numerical values in the graphs, did you eyeball it?

**Comment by ostaquet** [comment]
Indeed the data sheet doesn't provide any numerical values.

The trick is:
1. Open the PDF of the data sheet and zoom on the chart.
2. Screenshot the chart.
3. Prepare an Excel sheet with the data points you need.
4. Make a chart in Excel and put the screenshot on the chart with some transparency.
5. Adjust the data point to match the screenshot

Not 100% accurate but quite close to the values of the original chart ;-)
