### ISSUE TITLE
doesn't print correctly

### ISSUE THREAD

**Issue by tamalatomico** [ostaquet/Arduino-MQ131-driver#44]
I'm trying to calibrate one MQ131 (black bakelite version) the program upload correctly, the sensor gets "heated" and everything seems correct but it's printing just nonsense characters:

**⸮S⸮W⸮ude⸮⸮Wd,$5uu$$u⸮⸮⸮u⸮dWu%wdW5d⸮udW⸮u⸮u⸮5$⸮`5(dd5⸮⸮5$($d**

I changed the pins connectors, the cables, the protoboard, even some words:

  Serial.println("CALIBRANDO...");

but it doesn't seem to solve the problem. 
 
I'm at programming & writing on english

**Comment by ostaquet** [comment]
I don't think it is related to the MQ131 or the driver.
Probably an issue with the baud rate of the Serial or an issue in the main program.
