### ISSUE TITLE
PPB values

### ISSUE THREAD

**Issue by TheMrguiller** [ostaquet/Arduino-MQ131-driver#48]
I am new to the mq family and It seems I am not getting the basics. I have my sensor running an operating but I have some issues related to ppb. In the datasheet of the MQ-131 It says that the output is range between 10-100 ppm. These range of values seems odd due to the fact that 0,018 ppm is the limit intake for humans. Is the graphic badly design and the real values are to be taken in ppb? I need some help with these. 

Thank you so much

**Comment by ostaquet** [comment]
It depends on the type of sensor you're using. There are (at least) three kind of MQ131 as described on the README.md page. That's why there are some data sheets with figures in PPB and others with figures in PPM.
