### ISSUE TITLE
confusing wiring diagram

### ISSUE THREAD

**Issue by ghost** [ostaquet/Arduino-MQ131-driver#49]
The changing colors of the wires in the wiring diagram in READ Me make it very confusing. I am legitimately unable to tell which wires go where.

**Comment by ostaquet** [comment]
I just reviewed the diagrams in the readme and there are not so much wires.
Can you be more specific in order to improve?

**Comment by NXTkoji** [comment]
Hello. Thanks for offering this helpful library. If I connect external (not from Arduino board) 5V to MQ-131 sensor and heater pins, and also connect MQ-131 ground pin to external Ground, will I still need to connect external Ground to Arduino board Ground?

**Comment by ostaquet** [comment]
@NXTkoji Answered in #53 ;-)
