### ISSUE TITLE
Low Concentration Qualitative Detection MQ131 with ESP32

### ISSUE THREAD

**Issue by dvJoshr** [ostaquet/Arduino-MQ131-driver#56]
Hello, I need your help.
I need integrate a MQ131 sensor With Esp32, but I am working with this model: 
![HTB1zOUgnXooBKNjSZFPq6xa2XXae](https://user-images.githubusercontent.com/45470824/187569768-c8a3305a-bb8d-4950-ab2c-3962e596f6c6.jpg)
And I dont know how add the MOSFET in the conection.
Can I still use a library? And what would happen with that connection to the voltage divider?
I'm a amateur in this area.
Sorry for my English.
Thank.

**Comment by ostaquet** [comment]
Do you have the datasheet for this breakout board?

I see a potentiometer, probably to setup the load resistance (RL) but without details, it is complex to answer.

**Comment by ostaquet** [comment]
Closed as won't fix, missing info.
