### ISSUE TITLE
control temperature

### ISSUE THREAD

**Issue by nuo2004lyn** [ostaquet/Arduino-MQ131-driver#59]
I have a question about the heating temperature. There is an optimum heating temperature when the sensor is working. For example, some materials need to be heated at 100oC to detect the concentration. How about this MQ131 sensor? How can I control the temperature? Thank you.

**Comment by ostaquet** [comment]
There is no specific information in the data sheet except a duration of pre-heating (48 hours) under 5V. According to my knowledge, there is no temperature sensor with the MQ131 and it is difficult to measure the temperature considering the form factor. In all my tests, I put 5V on the sensor for 48 hours and the results seem consistent. You can maybe have additional information directly to the manufacturer.
