### ISSUE TITLE
Bluetooth hc-05

### ISSUE THREAD

**Issue by EmbeddyE** [ostaquet/Arduino-MQ131-driver#60]
So everything it's fine when I'm using the Serial monitor on the arduino IDE, but when it comes to using bluetooth to show values into an android bluetooth receiver, there's no value output on my android terminal( I'm using Ardutooth). I'm using the following code:
`#include <MQ131.h>
#include <SoftwareSerial.h>

SoftwareSerial B(10, 11); // RX, TX

void setup() {
  Serial.begin(9600);
  B.begin(9600); // Bluetooth communication
  MQ131.begin(2, A0, LOW_CONCENTRATION, 1000000);  
  MQ131.calibrate();
}

void loop() {
  MQ131.sample();
  B.print(MQ131.getO3(UG_M3));
  B.print(" ug/m3");
  B.print(";");
  delay(20);
}
`

**Comment by ostaquet** [comment]
As the library is working fine without the Bluetooth communication, it is probably linked to the Bluetooth communication and not the library.
