### ISSUE TITLE
Problem reading ozone with library...

### ISSUE THREAD

**Issue by MartinPellizzer** [ostaquet/Arduino-MQ131-driver#7]
Hi, I greatly appreciate your library and the work you did with the MQ131, because I have serious problems making it works.

I tried the default diagram given by the manufacturer, but the ADC readings shift too much during time and I can't have a stable reading, so I'm looking forward your library.

I tested your library and used your wiring diagram, but I'm having 1 issue. I can pass the calibration process and get 0.01ppm in clean air, but when I blow ozone to the sensor the reading doesn't change. I exposed the sensor to a lot of ozone for hours, but no results. Am I missing something? The sensor doesn't get hot like it does with the manufacturer diagram, but it stays almost cold. Is it normal behaviour?

Your support would be a life-save for me.

Kind regards,
Martin

**Comment by ostaquet** [comment]
Hi Martin,
The first thing to check is the type of sensor you're using. There are at least 3 different MQ131 on the market. The most common are the black bakelite (low concentration) and the metal one (high concentration). In normal air, you should use the low concentration version; for industrial usage, you should use the high concentration. Using the high concentration version for air quality control will not work.
Second thing to not forget is the burn-in time. You should pre-heat your sensor by applying 5v on the heater for 48h to have consistent values over time.
To conclude, the sensor should be hot during the heating process. If it's staying cold, there is an issue (wiring probably, you can test is with a multimeter).
KR,
Olivier
